CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name varchar(20),
    date_of_birth Date,
    escape_attempts INT,
    neutered Bit,
    weight_kg Decimal,
     PRIMARY KEY (id)
);

/*Add a column species of type string to your animals table. Modify your schema.sql file**/
ALTER TABLE animals
ADD species varchar(30);